---
- name: Deploy Docker Compose Application
  hosts: web
  become: yes
  tasks:
    - name: Update apt and install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-uname -s-uname -m
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy Dockerfile to EC2
      copy:
        src: /path/to/your/Dockerfile
        dest: /home/ubuntu/Dockerfile

    - name: Copy Docker Compose file to EC2
      copy:
        src: /path/to/your/docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Build Docker image
      command: docker-compose -f /home/ubuntu/docker-compose.yml build

    - name: Run Docker Compose
      command: docker-compose -f /home/ubuntu/docker-compose.yml up -d