version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_PATH=/flask-data
    volumes:
      - ./data:/flask-data  # Map /flask-data to a persistent volume
    restart: always