version: "3.8"

services:
  flask-app:
    build: .
    container_name: flask-expense-tracker
    ports:
      - "5000:5000"
    volumes:
      - ./data:/flask-data
    environment:
      - DB_PATH=/flask-data
    restart: unless-stopped
